/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-05-22 10:12:40 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class chat_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n");
      out.write("<html>\n");
      out.write("<head>\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\n");
      out.write("<title>Insert title here</title>\n");
      out.write("<script type=\"text/javascript\" src=\"");
      out.print(request.getContextPath());
      out.write("/static/js/sockjs.js\"></script>\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery.min.js\"></script>\n");
      out.write("<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\n");
      out.write("<!-- 新 Bootstrap 核心 CSS 文件 -->\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap.min.css\">\n");
      out.write("<script type=\"text/javascript\">\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tvar websocket =null;\n");
      out.write("\tif (window['WebSocket']) {\n");
      out.write("\t\t//alert( window.location.host);\n");
      out.write("\t\t//WebSocket连接\n");
      out.write("\t\twebsocket = new WebSocket('ws://' + window.location.host + '/haidong-chat/marco?roomId=5ac20f85e70c4a0eb19802ea28ae84e0&type=1');\n");
      out.write("\t}\n");
      out.write("\telse\n");
      out.write("\t\t//SockeJS连接\n");
      out.write("\t\twebsocket = new SockJS('/haidong-h5/js/marco');\n");
      out.write("\t\t\n");
      out.write("\n");
      out.write("\twebsocket.onopen = function() {\n");
      out.write("\t\talert('Opening');\n");
      out.write("\t\t//websocket.send(\"\");\n");
      out.write("\t\t//sayMarco();\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\twebsocket.onmessage = function(e) {\n");
      out.write("\t\talert('Received message: '+e.data);\n");
      out.write("\t\t$('#msg').append(\"<li>\"+e.data+\"</li>\");\n");
      out.write("\t\tvar data = $.parseJSON(e.data);\n");
      out.write("\t\t$('#userName').html(data.data.userName);\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\twebsocket.onclose = function() {\n");
      out.write("\t\talert('Closing');\n");
      out.write("\t};\n");
      out.write("\t\n");
      out.write("\tfunction sayMarco() {\n");
      out.write("\t\talert('Sending Marco!');\n");
      out.write("\t\twebsocket.send(\"Marco!\");\n");
      out.write("\t}  \n");
      out.write("\t\n");
      out.write("\tfunction checkType(){\n");
      out.write("\t\t\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction sendText(){\n");
      out.write("\t\t//websocket.send($('input').val());\n");
      out.write("\t\t//if($('text'))S\n");
      out.write("\t\t$.get(\"chat\",{msg:$('input').val(),userId:\"68065618dccf41eb8f3c502a5d1ed509\",roomId:\"5ac20f85e70c4a0eb19802ea28ae84e0\",money:1000});\n");
      out.write("\t\t$('input').val('');\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\tfunction sendGift(){\n");
      out.write("\t\t//websocket.send($('input').val());\n");
      out.write("\t\t$.get(\"gift\",{giftId:$('#gift').val(),openId:\"oz_1CwX7c-Nft60uNSo1kRfJjnNU\",roomId:1,text:\"百年好合\"});\n");
      out.write("\t\tconsole.log($('#gift').val());\n");
      out.write("\t}\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\t\n");
      out.write("\tfunction getAllUsers() {\n");
      out.write("\t\t $.ajax({  \n");
      out.write("           url:'http://192.168.1.107:8080/haidong-chat/draw?liveid=5ac20f85e70c4a0eb19802ea28ae84e0',  \n");
      out.write("           type: \"get\",   \n");
      out.write("           dataType: \"jsonp\",\n");
      out.write("           jsonp:\"callback\",//服务端用于接收callback调用的function名的参数   \n");
      out.write("           jsonpCallback: \"success_jsonpCallback\", //callback的function名称,服务端会把名称和data一起传递回来  \n");
      out.write("           success: function (data) { \n");
      out.write("           \tvar json =  JSON.stringify(data);\n");
      out.write("           \talert(json);\n");
      out.write("           },  \n");
      out.write("           error: function(){alert('Error123');}  \n");
      out.write("   });  \n");
      out.write("\t}\t\n");
      out.write("</script>\n");
      out.write("\t\n");
      out.write("</head>\n");
      out.write("<body>\n");
      out.write("\t<div id=\"userInfo\">\n");
      out.write("\t\t\n");
      out.write("\t</div>\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"getAllUsers();\" id=\"draw\">发送</button><br>\n");
      out.write("\t\n");
      out.write("\t<input class=\"form-controll\" type=\"text\">\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\" onclick=\"sendText()\" id=\"text\">发送</button><br>\n");
      out.write("\t<select\tid=\"gift\" class=\"form-controll\">\n");
      out.write("\t\t<option value=\"flower\">鲜花</option>\n");
      out.write("\t\t<option value=\"car\">跑车</option>\n");
      out.write("\t\t<option value=\"love\">爱心</option>\n");
      out.write("\t</select>\n");
      out.write("\t<button type=\"button\" class=\"btn btn-primary\"  onclick=\"sendGift()\">发送礼物</button><br>\n");
      out.write("\t<ul id=\"msg\">\n");
      out.write("\t</ul>\n");
      out.write("</body>\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
