/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.85
 * Generated at: 2018-05-22 09:42:21 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class view_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write('\r');
      out.write('\n');

	String path = request.getContextPath();
	String basePath = request.getScheme() + "://" + request.getServerName() + ":" + request.getServerPort()
			+ path + "/";

      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\">\r\n");
      out.write("<title>Insert title here</title>\r\n");
      out.write("<script type=\"text/javascript\"\r\n");
      out.write("\tsrc=\"");
      out.print(request.getContextPath());
      out.write("/static/js/sockjs.js\"></script>\r\n");
      out.write("<script type=\"text/javascript\" src=\"static/js/jquery.min.js\"></script>\r\n");
      out.write("<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->\r\n");
      out.write("<script src=\"static/js/bootstrap.min.js\"></script>\r\n");
      out.write("<!-- 新 Bootstrap 核心 CSS 文件 -->\r\n");
      out.write("<link rel=\"stylesheet\" href=\"static/css/bootstrap.min.css\">\r\n");
      out.write("<style type=\"text/css\">\r\n");
      out.write("* {\r\n");
      out.write("\tmargin: 0;\r\n");
      out.write("\tpadding: 0;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("html {\r\n");
      out.write("\tfont-size: 10px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("h4 {\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tfont-size: 3rem;\r\n");
      out.write("\tpadding: 30px;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp {\r\n");
      out.write("\twidth: 1400px;\r\n");
      out.write("\toverflow: hidden;\r\n");
      out.write("\tmargin: 0 auto;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp .player1 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder: 2px solid #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp .player2 {\r\n");
      out.write("\tfloat: left;\r\n");
      out.write("\tpadding: 20px;\r\n");
      out.write("\tborder: 2px solid #fff;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp .player1.on {\r\n");
      out.write("\tborder-color: #ff5384;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp .player2.on {\r\n");
      out.write("\tborder-color: #ff5384;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write(".warp p {\r\n");
      out.write("\twidth:600px;\r\n");
      out.write("\tfont-size: 2rem;\r\n");
      out.write("\tpadding: 15px 0;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tword-break: break-all;\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".warp .btn {\r\n");
      out.write("\tcursor: pointer;\r\n");
      out.write("\theight: 50px;\r\n");
      out.write("\twidth: 150px;\r\n");
      out.write("\tline-height: 50px;\r\n");
      out.write("\tbackground-color: #ff5384;\r\n");
      out.write("\tborder-radius: 5px;\r\n");
      out.write("\ttext-align: center;\r\n");
      out.write("\tcolor: #fff;\r\n");
      out.write("\tfont-size: 2rem;\r\n");
      out.write("\tmargin-left: 50%;\r\n");
      out.write("\ttransform: translateX(-50%);\r\n");
      out.write("\tpadding:0\r\n");
      out.write("}\r\n");
      out.write("\r\n");
      out.write(".noevent {\r\n");
      out.write("\tpointer-events: none;\r\n");
      out.write("}\r\n");
      out.write("</style>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t\r\n");
      out.write("\t<h4>当前直播源:<span id=\"liveId\">Live01</span></h4>\r\n");
      out.write("\r\n");
      out.write("\t<div class=\"warp\">\r\n");
      out.write("\t\t<div class=\"player1 on\">\r\n");
      out.write("\t\t\t<div id=\"live1\"></div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<p>信号源:live01</p>\r\n");
      out.write("\r\n");
      out.write("\t\t\t<div class=\"btn\" onclick=\"live(1)\">切换</div>\r\n");
      out.write("\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"player2\">\r\n");
      out.write("\t\t\t<div id=\"live2\"></div>\r\n");
      out.write("\t\t\t<p>信号源:live03</p>\r\n");
      out.write("\t\t\t<div class=\"btn\" onclick=\"live(3)\">切换</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t</div>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\" src=\"");
      out.print(basePath);
      out.write("/static/ckplayer/ckplayer/ckplayer.js\" charset=\"utf-8\"></script>\r\n");
      out.write("\t<script>\r\n");
      out.write("\t\tvar live01='http://live.hidongtv.com/haidongTV/live01.m3u8';\r\n");
      out.write("\t\tvar live03='http://live.hidongtv.com/haidongTV/live03.m3u8';\r\n");
      out.write("\t\tvar roomdId = 'cda64caea5624102bc6ff1471cb8fedc';\r\n");
      out.write("\t\t\r\n");
      out.write("\t\t$('.player1 p').html(live01);\r\n");
      out.write("\t\t$('.player2 p').html(live03);\r\n");
      out.write("\t\tfunction getCurrentLive() {\r\n");
      out.write("\t\t\t$.get(\"getCurrentLive\", {\r\n");
      out.write("\t\t\t\troomId : roomdId\r\n");
      out.write("\t\t\t}, function(result) {\r\n");
      out.write("\t\t\t\t$(\"#liveId\").html(result);\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\tif(result==live01){\r\n");
      out.write("\t\t\t\t\t$('.player2').removeClass('on');\r\n");
      out.write("\t\t\t\t\t$('.player1').addClass('on');\r\n");
      out.write("\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t},1000)\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t\r\n");
      out.write("\t\t\t\t}else if(result==live03){\r\n");
      out.write("\t\t\t\t\t$('.player1').removeClass('on');\r\n");
      out.write("\t\t\t\t\t$('.player2').addClass('on');\r\n");
      out.write("\t\t\t\t\t\tsetTimeout(function(){\r\n");
      out.write("\t\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t},1000)\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\tgetCurrentLive();\r\n");
      out.write("\r\n");
      out.write("\t\tfunction live(x) {\r\n");
      out.write("\t\t\tvar c;\r\n");
      out.write("\t\t\tx == 1 ? c = live01\r\n");
      out.write("\t\t\t\t\t: c = live03;\r\n");
      out.write("\t\t\t$.get(\"changeVideo\", {\r\n");
      out.write("\t\t\t\troomId : roomdId,\r\n");
      out.write("\t\t\t\tvideoUrl : c\r\n");
      out.write("\t\t\t},function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t\t\t\t\t//$('#liveId').html('Live0' + x);\r\n");
      out.write("\t\t\t\t\t$('#liveId').html(c);\r\n");
      out.write("\t\t\t\t\tif(x==3){\r\n");
      out.write("\t\t\t\t\t\t$('.player1').removeClass('on');\r\n");
      out.write("\t\t\t\t\t\t$('.player2').addClass('on');\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t\t\t\t\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('.player2').removeClass('on');\r\n");
      out.write("\t\t\t\t\t\t$('.player1').addClass('on');\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t\t\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t$.get(\"changeVideo\", {\r\n");
      out.write("\t\t\t\troomId : roomdId,\r\n");
      out.write("\t\t\t\tvideoUrl : c\r\n");
      out.write("\t\t\t},function(data){\r\n");
      out.write("\t\t\t\tconsole.log(data);\r\n");
      out.write("\t\t\t\tif(data==\"success\"){\r\n");
      out.write("\t\t\t\t\t//$('#liveId').html('Live0' + x);\r\n");
      out.write("\t\t\t\t\t$('#liveId').html(c);\r\n");
      out.write("\t\t\t\t\tif(x==3){\r\n");
      out.write("\t\t\t\t\t\t$('.player1').removeClass('on');\r\n");
      out.write("\t\t\t\t\t\t$('.player2').addClass('on');\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t}else{\r\n");
      out.write("\t\t\t\t\t\t$('.player2').removeClass('on');\r\n");
      out.write("\t\t\t\t\t\t$('.player1').addClass('on');\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a1').changeVolume(100)\r\n");
      out.write("\t\t\t\t\t\tCKobject.getObjectById('ckplayer_a2').changeVolume(0)\r\n");
      out.write("\t\t\t\t\t}\r\n");
      out.write("\t\t\t\t}\r\n");
      out.write("\t\t\t});\r\n");
      out.write("\t\t\t\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("\t<script type=\"text/javascript\">\r\n");
      out.write("\t\tvar flashvars = {\r\n");
      out.write("\t\t\t//f:'http://img.ksbbs.com/asset/Mon_1605/0ec8cc80112a2d6.mp4',\r\n");
      out.write("\t\t\tf : '");
      out.print(basePath);
      out.write("/static/ckplayer/m3u8.swf',\r\n");
      out.write("\t\t\ta : live01,\r\n");
      out.write("\t\t\tc : 0,\r\n");
      out.write("\t\t\ts : 4,\r\n");
      out.write("\t\t\ti : 'http://www.ckplayer.com/static/images/cqdw.jpg',\r\n");
      out.write("\t\t\tlv : '1',\r\n");
      out.write("\t\t\tp : '1'\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar params = {\r\n");
      out.write("\t\t\tbgcolor : '#FFF',\r\n");
      out.write("\t\t\tallowFullScreen : true,\r\n");
      out.write("\t\t\tallowScriptAccess : 'always',\r\n");
      out.write("\t\t\twmode : 'transparent'\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tCKobject.embedSWF(\"");
      out.print(basePath);
      out.write("/static/ckplayer/ckplayer/ckplayer.swf\", 'live1', 'ckplayer_a1',\r\n");
      out.write("\t\t\t\t'600', '400', flashvars, params);\r\n");
      out.write("\r\n");
      out.write("\t\tvar flashvars1 = {\r\n");
      out.write("\t\t\t//f:'http://img.ksbbs.com/asset/Mon_1605/0ec8cc80112a2d6.mp4',\r\n");
      out.write("\t\t\tf : '");
      out.print(basePath);
      out.write("/static/ckplayer/m3u8.swf',\r\n");
      out.write("\t\t\ta : live03,\r\n");
      out.write("\t\t\tc : 0,\r\n");
      out.write("\t\t\ts : 4,\r\n");
      out.write("\t\t\ti : 'http://www.ckplayer.com/static/images/cqdw.jpg',\r\n");
      out.write("\t\t\tlv : '1',\r\n");
      out.write("\t\t\tp : '1'\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tvar params1 = {\r\n");
      out.write("\t\t\tbgcolor : '#FFF',\r\n");
      out.write("\t\t\tallowFullScreen : true,\r\n");
      out.write("\t\t\tallowScriptAccess : 'always',\r\n");
      out.write("\t\t\twmode : 'transparent',\r\n");
      out.write("\t\t\tlogo : 'null',\r\n");
      out.write("\t\t\tcontrolBarShow : false\r\n");
      out.write("\t\t};\r\n");
      out.write("\t\tCKobject.embedSWF(\"");
      out.print(basePath);
      out.write("/static/ckplayer/ckplayer/ckplayer.swf\", 'live2', 'ckplayer_a2',\r\n");
      out.write("\t\t\t\t'600', '400', flashvars1, params1);\r\n");
      out.write("\t\t\r\n");
      out.write("\r\n");
      out.write("\t\tfunction ckmarqueeadv() {\r\n");
      out.write("\t\t\treturn ''\r\n");
      out.write("\t\t}\r\n");
      out.write("\t</script>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
